"""add colour_code to sales_logs

Revision ID: 25c2f93afbbe
Revises: 56ef35718a8b
Create Date: 2025-06-24 19:00:53.684409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c2f93afbbe'
down_revision: Union[str, None] = '56ef35718a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_logs', sa.Column('colour_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_logs', 'colour_code')
    # ### end Alembic commands ###
