"""initial fresh migration with color-code pairs

Revision ID: 33afa276580f
Revises: 8a235f2f7d13
Create Date: 2025-06-24 17:13:16.325040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33afa276580f'
down_revision: Union[str, None] = '8a235f2f7d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
