"""add colour_code to inward_logs

Revision ID: 56ef35718a8b
Revises: 33afa276580f
Create Date: 2025-06-24 18:04:50.446698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ef35718a8b'
down_revision: Union[str, None] = '33afa276580f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inward_logs', sa.Column('colour_code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inward_logs', 'colour_code')
    # ### end Alembic commands ###
