"""Add customer and agency tables

Revision ID: 7bc42eb55b76
Revises: 3ce267b9d991
Create Date: 2025-06-28 03:08:43.970004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc42eb55b76'
down_revision: Union[str, None] = '3ce267b9d991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=False),
    sa.Column('owner_mobile', sa.String(), nullable=False),
    sa.Column('accounts_mobile', sa.String(), nullable=False),
    sa.Column('days_of_payment', sa.Integer(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('region_covered', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_agency_name'), 'agencies', ['agency_name'], unique=True)
    op.create_index(op.f('ix_agencies_id'), 'agencies', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('referrer', sa.String(), nullable=False),
    sa.Column('owner_mobile', sa.String(), nullable=False),
    sa.Column('accounts_mobile', sa.String(), nullable=False),
    sa.Column('days_of_payment', sa.Integer(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_store_name'), 'customers', ['store_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_store_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_agencies_id'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_agency_name'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
