"""make order_number unique and not nullable

Revision ID: 9a30eb1e092e
Revises: 423b3693f971
Create Date: 2025-06-30 15:54:41.580454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a30eb1e092e'
down_revision: Union[str, None] = '423b3693f971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_order_number_finyear', 'orders', ['order_number', 'financial_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_number_finyear', 'orders', type_='unique')
    op.alter_column('orders', 'order_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
